-- NGO Beneficiary Management System Schema (PostgreSQL)
-- Converted from MySQL schema.sql

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  full_name varchar(100) NOT NULL,
  role varchar(10) NOT NULL DEFAULT 'user' CHECK (role IN ('admin','user')),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, username, password_hash, full_name, role, created_at, updated_at) VALUES
(1, 'admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'System Administrator', 'admin', '2026-02-08 10:00:00', '2026-02-08 10:00:00'),
(2, 'user', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Field Officer', 'user', '2026-02-08 10:00:00', '2026-02-08 10:00:00')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users','id'), (SELECT COALESCE(MAX(id), 1) FROM users));

CREATE TABLE IF NOT EXISTS households (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  household_code varchar(20) NOT NULL UNIQUE,
  family_size integer NOT NULL DEFAULT 1,
  vulnerability_status varchar(10) NOT NULL DEFAULT 'low' CHECK (vulnerability_status IN ('low','medium','high','critical')),
  income_level varchar(10) NOT NULL DEFAULT 'none' CHECK (income_level IN ('none','very_low','low','medium','high')),
  location text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS beneficiaries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id varchar(20) NOT NULL UNIQUE,
  full_name varchar(100) NOT NULL,
  age integer NOT NULL,
  gender varchar(10) NOT NULL CHECK (gender IN ('male','female','other')),
  address text NOT NULL,
  id_number varchar(50) UNIQUE,
  photo_path varchar(255),
  household_id integer NULL,
  registered_at timestamp DEFAULT CURRENT_TIMESTAMP,
  status varchar(15) NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','graduated','suspended')),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp NULL,
  CONSTRAINT fk_beneficiaries_household FOREIGN KEY (household_id) REFERENCES households(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_beneficiaries_household_id ON beneficiaries(household_id);

CREATE TABLE IF NOT EXISTS baseline_data (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id integer NOT NULL,
  education_level varchar(15) CHECK (education_level IN ('none','primary','secondary','tertiary','vocational')),
  health_status text,
  livelihood_info text,
  nutrition_status varchar(25) DEFAULT 'normal' CHECK (nutrition_status IN ('normal','moderate_malnutrition','severe_malnutrition')),
  monthly_income numeric(10,2) DEFAULT 0.00,
  assets text,
  assessment_date date NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_baseline_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_baseline_beneficiary_id ON baseline_data(beneficiary_id);

CREATE TABLE IF NOT EXISTS projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code varchar(20) NOT NULL UNIQUE,
  project_name varchar(100) NOT NULL,
  description text,
  start_date date NOT NULL,
  end_date date,
  status varchar(15) NOT NULL DEFAULT 'planning' CHECK (status IN ('planning','active','completed','on_hold','cancelled')),
  location text,
  budget numeric(12,2) DEFAULT 0.00,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interventions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL,
  service_type varchar(20) NOT NULL CHECK (service_type IN ('cash_assistance','food_aid','iga_support','training','education','health_subsidy','other')),
  description text,
  budget_allocated numeric(10,2) DEFAULT 0.00,
  target_beneficiaries integer DEFAULT 0,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_interventions_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_interventions_project_id ON interventions(project_id);

CREATE TABLE IF NOT EXISTS beneficiary_projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id integer NOT NULL,
  project_id integer NOT NULL,
  enrollment_date date NOT NULL,
  participation_status varchar(15) NOT NULL DEFAULT 'enrolled' CHECK (participation_status IN ('enrolled','active','completed','dropped_out')),
  notes text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_enrollment UNIQUE (beneficiary_id, project_id),
  CONSTRAINT fk_bp_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE,
  CONSTRAINT fk_bp_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bp_project_id ON beneficiary_projects(project_id);

CREATE TABLE IF NOT EXISTS attendance (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id integer NOT NULL,
  project_id integer NOT NULL,
  event_type varchar(20) NOT NULL CHECK (event_type IN ('training','community_event','distribution','meeting')),
  event_date date NOT NULL,
  attendance_status varchar(10) NOT NULL DEFAULT 'absent' CHECK (attendance_status IN ('present','absent','excused')),
  remarks text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_attendance_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE,
  CONSTRAINT fk_attendance_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_attendance_beneficiary_id ON attendance(beneficiary_id);
CREATE INDEX IF NOT EXISTS idx_attendance_project_id ON attendance(project_id);

CREATE TABLE IF NOT EXISTS case_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id integer NOT NULL,
  user_id integer NOT NULL,
  note_type varchar(15) NOT NULL DEFAULT 'general' CHECK (note_type IN ('general','follow_up','counseling','incident','assessment')),
  content text NOT NULL,
  follow_up_date date,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_case_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE,
  CONSTRAINT fk_case_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_case_notes_beneficiary_id ON case_notes(beneficiary_id);
CREATE INDEX IF NOT EXISTS idx_case_notes_user_id ON case_notes(user_id);

CREATE TABLE IF NOT EXISTS alerts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id integer NOT NULL,
  alert_type varchar(20) NOT NULL CHECK (alert_type IN ('overdue_followup','high_risk','missing_data','inactive','other')),
  message text NOT NULL,
  priority varchar(10) NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high','critical')),
  is_resolved boolean NOT NULL DEFAULT FALSE,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  resolved_at timestamp,
  CONSTRAINT fk_alerts_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_alerts_beneficiary_id ON alerts(beneficiary_id);

CREATE TABLE IF NOT EXISTS referrals (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id integer NOT NULL,
  referral_type varchar(15) NOT NULL CHECK (referral_type IN ('health','psychosocial','legal','education','livelihood','other')),
  referred_to varchar(150) NOT NULL,
  reason text NOT NULL,
  referral_date date NOT NULL,
  status varchar(15) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','in_progress','completed','cancelled')),
  outcome text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_referrals_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_referrals_beneficiary_id ON referrals(beneficiary_id);

COMMIT;
